MetaArgs: null
Stages:
- BaseName: jupyter/base-notebook:cd158647fb94
  Commands:
  - CmdLine:
    - conda install -y -q --freeze-installed -c ome omero-py 'notebook>=6.0.2'
    Name: run
    PrependShell: true
  - CmdLine:
    - python3 -mpip install fs-omero-pyfs jupyter-pyfilesystem
    Name: run
    PrependShell: true
  - Env:
    - Key: TRAITLETS_APPLICATION_RAISE_CONFIG_FILE_ERROR
      Value: "true"
    Name: env
  - CmdLine:
    - mkdir -p $HOME/.jupyter/jupyter_notebook_config.d
    Name: run
    PrependShell: true
  - CmdLine:
    - '/bin/echo -e ''from glob import glob\nfor f in glob(".jupyter/jupyter_notebook_config.d/*py"):
      exec(open(f).read())'' >>     $HOME/.jupyter/jupyter_notebook_config.py'
    Name: run
    PrependShell: true
  - Chown: ""
    Name: add
    SourcesAndDest:
    - jupyter_notebook_config.py
    - $HOME/.jupyter/jupyter_notebook_config.d/contentsmanager.py
  From:
    Image: jupyter/base-notebook:cd158647fb94
  Name: ""
  Platform: ""
  SourceCode: FROM jupyter/base-notebook:cd158647fb94
